### ISSUE TITLE
Wrapping model for MNIST Scikit-learn doesn't work

### ISSUE THREAD

**Issue by smolina74** [kubeflow/example-seldon#13]
When trying to serve the MNIST Scikit-learn model (kubeflow-seldon example), using the latest code there (which is using s2i for building images)  I'm getting the following error:

santiago@santiago-Inspiron-5559:~$ kubectl logs seldon-sk-deploy-wc9qg-927719684 main
Connecting to github.com (192.30.253.112:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
tar: can't open 'source-to-image-v1.1.9a-40ad911d-linux-amd64.tar.gz': No such file or directory
Cannot connect to the Docker daemon at tcp://127.0.0.1:2375. Is the docker daemon running?
Cannot connect to the Docker daemon at tcp://127.0.0.1:2375. Is the docker daemon running?
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
./wrap.sh: line 14: ./s2i: not found
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
Pushing image to santiagomol40/skmnistclassifier_runtime:0.1
Login Succeeded
The push refers to a repository [docker.io/santiagomol40/skmnistclassifier_runtime]
An image does not exist locally with the tag: santiagomol40/skmnistclassifier_runtime

Looks like the container in charge of running s2i doesn't have SSL support.

**Comment by ukclivecox** [comment]
There are two issues here. SSL needed as you say and also an underlying issue with DOCKER_HOST values not working with s2i.
https://github.com/openshift/source-to-image/issues/871

Should be able to push a fix for both.
