### ISSUE TITLE
[prow] Fix the typo in kubernetes/test-infra and setup test

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/example-seldon#16]
https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L122

The name of the repository in test-infra is wrong and we need to fix it. Then we should setup test cases for the repository and use tide to auto-merge PRs. Currently the [commit history](https://github.com/kubeflow/example-seldon/commits/master) of the repository is hard to understand.

**Comment by ukclivecox** [comment]
Can we clarify if we are discussing the correct things. There is 
 1. The seldon ksonnet packages which are part of the kubeflow registry : https://github.com/kubeflow/kubeflow/tree/master/kubeflow/seldon
 1. This repo which is an example end-to-end app like others in https://github.com/kubeflow/examples

**Comment by gaocegege** [comment]
Yeah, I understand. I mean that we misspell the repo name in kubernetes test-infra. And we should fix it, to import tide to auto-merge PRs as other repositories in our community :smile:
