### ISSUE TITLE
Training error on all frameworks

### ISSUE THREAD

**Issue by DavidLangworthy** [kubeflow/example-seldon#34]
And I am running into an error training the model with all the different frameworks.  This is a new installation and this is my first time through, so I expect that there is a missing dependency or something, but I cannot figure out how to debug this and find out what the problem it.  The error does not occur until about 4 hours into a run, so I can replicate it reliably, but it takes a long time to do so.

Here is the error:

Name:                kubeflow-tf-train-bp9ln
Namespace:           kubeflow
ServiceAccount:      default
Status:              Failed
Message:             child 'kubeflow-tf-train-bp9ln-480988007' failed
Created:             Tue Apr 02 21:03:12 +0000 (1 week ago)
Started:             Tue Apr 02 21:03:12 +0000 (1 week ago)
Finished:            Tue Apr 02 21:03:21 +0000 (1 week ago)
Duration:            9 seconds
Parameters:          
  tfjob-version-hack: 1
  version:           0.1
  github-user:       kubeflow
  github-revision:   master
  docker-user:       seldonio
  build-push-image:  false

STEP                        PODNAME                            DURATION  MESSAGE
 ✖ kubeflow-tf-train-bp9ln                                               child 'kubeflow-tf-train-bp9ln-480988007' failed
 ├---○ build-push                                                        when 'false == true' evaluated false
 └---✖ train                kubeflow-tf-train-bp9ln-480988007  8s        Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": tfjobs.kubeflow.org "mnist-train-1" already exists

**Comment by ukclivecox** [comment]
It looks like the tfjob already exists. Have you checked `kubectl get tfjob` ?

**Comment by DavidLangworthy** [comment]
@cliveseldon there was a duplicate tfjob, thank you.  I've brought up a new cluster and gone through the install steps again, but am still getting an error.

Here's what I'm seeing. Any further suggestions?

!argo get kubeflow-tf-train-7w6r9
Name:                kubeflow-tf-train-7w6r9
Namespace:           kubeflow
ServiceAccount:      default
Status:              Failed
Message:             child 'kubeflow-tf-train-7w6r9-1033336217' failed
Created:             Thu Apr 18 18:08:52 +0000 (1 hour ago)
Started:             Thu Apr 18 18:08:53 +0000 (1 hour ago)
Finished:            Thu Apr 18 18:24:09 +0000 (53 minutes ago)
Duration:            15 minutes 16 seconds
Parameters:          
  tfjob-version-hack: 2
  version:           0.1
  github-user:       kubeflow
  github-revision:   master
  docker-user:       seldonio
  build-push-image:  false

STEP                        PODNAME                             DURATION  MESSAGE
 ✖ kubeflow-tf-train-7w6r9                                                child 'kubeflow-tf-train-7w6r9-1033336217' failed
 ├---○ build-push                                                         when 'false == true' evaluated false
 └---✖ train                kubeflow-tf-train-7w6r9-1033336217  15m       timed out waiting for the condition

!argo logs -w kubeflow-tf-train-7w6r9
train:	time="2019-04-18T18:09:06Z" level=info msg="Creating a docker executor"
train:	time="2019-04-18T18:09:06Z" level=info msg="Executor (version: v2.2.0, build_date: 2018-08-30T08:52:54Z) initialized with template:\narchiveLocation:\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: mlpipeline-minio-artifact\n    bucket: mlpipeline\n    endpoint: minio-service.kubeflow:9000\n    insecure: true\n    key: artifacts/kubeflow-tf-train-7w6r9/kubeflow-tf-train-7w6r9-1033336217\n    secretKeySecret:\n      key: secretkey\n      name: mlpipeline-minio-artifact\ninputs: {}\nmetadata: {}\nname: tfjob\noutputs: {}\nresource:\n  action: create\n  manifest: \"apiVersion: \\\"kubeflow.org/v1beta1\\\"\\nkind: \\\"TFJob\\\"\\nmetadata: \\n  name:\n    mnist-train-2\\n  ownerReferences:\\n  - apiVersion: argoproj.io/v1alpha1\\n    kind:\n    Workflow\\n    controller: true\\n    name: kubeflow-tf-train-7w6r9\\n    uid: 05e64d86-6205-11e9-a023-da0ed60f5a55\\nspec:\n    \\n  tfReplicaSpecs: \\n    Worker: \\n      replicas: 1\\n      template: \\n        spec:\n    \\n          containers: \\n            - \\n              image: \\\"seldonio/deepmnistclassifier_trainer:0.1\\\"\\n\n    \\             name: \\\"tensorflow\\\"\\n              volumeMounts: \\n                -\n    \\n                  mountPath: \\\"/data\\\"\\n                  name: \\\"persistent-storage\\\"\\n\n    \\         restartPolicy: \\\"OnFailure\\\"\\n          volumes: \\n            - \\n\n    \\             name: \\\"persistent-storage\\\"\\n              persistentVolumeClaim:\n    \\n                claimName: \\\"nfs-1\\\"\\n      tfReplicaType: \\\"MASTER\\\"\\n\"\n  successCondition: status.replicaStatuses.Worker.succeeded == 1\n"
train:	time="2019-04-18T18:09:06Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
train:	time="2019-04-18T18:09:06Z" level=info msg="kubectl create -f /tmp/manifest.yaml -o name"
train:	time="2019-04-18T18:09:08Z" level=info msg=tfjob.kubeflow.org/mnist-train-2
train:	time="2019-04-18T18:09:08Z" level=info msg="Waiting for conditions: status.replicaStatuses.Worker.succeeded==1"
train:	time="2019-04-18T18:09:08Z" level=info msg="kubectl get tfjob.kubeflow.org/mnist-train-2 -w -o json"
train:	time="2019-04-18T18:09:09Z" level=info msg="{\"apiVersion\": \"kubeflow.org/v1beta2\",\"kind\": \"TFJob\",\"metadata\": {\"creationTimestamp\": \"2019-04-18T18:09:08Z\",\"generation\": 1,\"name\": \"mnist-train-2\",\"namespace\": \"kubeflow\",\"ownerReferences\": [{\"apiVersion\": \"argoproj.io/v1alpha1\",\"controller\": true,\"kind\": \"Workflow\",\"name\": \"kubeflow-tf-train-7w6r9\",\"uid\": \"05e64d86-6205-11e9-a023-da0ed60f5a55\"}],\"resourceVersion\": \"4721\",\"selfLink\": \"/apis/kubeflow.org/v1beta2/namespaces/kubeflow/tfjobs/mnist-train-2\",\"uid\": \"0f2619f0-6205-11e9-a023-da0ed60f5a55\"},\"spec\": {\"tfReplicaSpecs\": {\"Worker\": {\"replicas\": 1,\"template\": {\"spec\": {\"containers\": [{\"image\": \"seldonio/deepmnistclassifier_trainer:0.1\",\"name\": \"tensorflow\",\"volumeMounts\": [{\"mountPath\": \"/data\",\"name\": \"persistent-storage\"}]}],\"restartPolicy\": \"OnFailure\",\"volumes\": [{\"name\": \"persistent-storage\",\"persistentVolumeClaim\": {\"claimName\": \"nfs-1\"}}]}},\"tfReplicaType\": \"MASTER\"}}},\"status\": {\"conditions\": [{\"lastTransitionTime\": \"2019-04-18T18:09:08Z\",\"lastUpdateTime\": \"2019-04-18T18:09:08Z\",\"message\": \"TFJob mnist-train-2 is created.\",\"reason\": \"TFJobCreated\",\"status\": \"True\",\"type\": \"Created\"}],\"replicaStatuses\": {\"Worker\": {}}}}"
train:	time="2019-04-18T18:09:09Z" level=info msg="success condition '{status.replicaStatuses.Worker.succeeded == [1]}' evaluated false"
train:	time="2019-04-18T18:09:09Z" level=info msg="0/1 success conditions matched"
train:	time="2019-04-18T18:10:45Z" level=warning msg="Json reader returned error EOF. Calling kill (usually superfluous)"
train:	time="2019-04-18T18:10:45Z" level=warning msg="Command for kubectl get -w for tfjob.kubeflow.org/mnist-train-2 exited. Getting return value using Wait"
train:	time="2019-04-18T18:10:45Z" level=info msg="readJSon failed for resource tfjob.kubeflow.org/mnist-train-2 but cmd.Wait for kubectl get -w command did not error"
train:	time="2019-04-18T18:10:45Z" level=info msg="Waiting for resource tfjob.kubeflow.org/mnist-train-2 resulted in retryable error EOF"
train:	time="2019-04-18T18:10:50Z" level=info msg="kubectl get tfjob.kubeflow.org/mnist-train-2 -w -o json"
train:	time="2019-04-18T18:10:51Z" level=info msg="{\"apiVersion\": \"kubeflow.org/v1beta2\",\"kind\": \"TFJob\",\"metadata\": {\"creationTimestamp\": \"2019-04-18T18:09:08Z\",\"generation\": 1,\"name\": \"mnist-train-2\",\"namespace\": \"kubeflow\",\"ownerReferences\": [{\"apiVersion\": \"argoproj.io/v1alpha1\",\"controller\": true,\"kind\": \"Workflow\",\"name\": \"kubeflow-tf-train-7w6r9\",\"uid\": \"05e64d86-6205-11e9-a023-da0ed60f5a55\"}],\"resourceVersion\": \"4721\",\"selfLink\": \"/apis/kubeflow.org/v1beta2/namespaces/kubeflow/tfjobs/mnist-train-2\",\"uid\": \"0f2619f0-6205-11e9-a023-da0ed60f5a55\"},\"spec\": {\"tfReplicaSpecs\": {\"Worker\": {\"replicas\": 1,\"template\": {\"spec\": {\"containers\": [{\"image\": \"seldonio/deepmnistclassifier_trainer:0.1\",\"name\": \"tensorflow\",\"volumeMounts\": [{\"mountPath\": \"/data\",\"name\": \"persistent-storage\"}]}],\"restartPolicy\": \"OnFailure\",\"volumes\": [{\"name\": \"persistent-storage\",\"persistentVolumeClaim\": {\"claimName\": \"nfs-1\"}}]}},\"tfReplicaType\": \"MASTER\"}}},\"status\": {\"conditions\": [{\"lastTransitionTime\": \"2019-04-18T18:09:08Z\",\"lastUpdateTime\": \"2019-04-18T18:09:08Z\",\"message\": \"TFJob mnist-train-2 is created.\",\"reason\": \"TFJobCreated\",\"status\": \"True\",\"type\": \"Created\"}],\"replicaStatuses\": {\"Worker\": {}}}}"
train:	time="2019-04-18T18:10:51Z" level=info msg="success condition '{status.replicaStatuses.Worker.succeeded == [1]}' evaluated false"
train:	time="2019-04-18T18:10:51Z" level=info msg="0/1 success conditions matched"
train:	time="2019-04-18T18:12:33Z" level=warning msg="Json reader returned error EOF. Calling kill (usually superfluous)"
train:	time="2019-04-18T18:12:33Z" level=warning msg="Command for kubectl get -w for tfjob.kubeflow.org/mnist-train-2 exited. Getting return value using Wait"
train:	time="2019-04-18T18:12:33Z" level=info msg="readJSon failed for resource tfjob.kubeflow.org/mnist-train-2 but cmd.Wait for kubectl get -w command did not error"
train:	time="2019-04-18T18:12:33Z" level=info msg="Waiting for resource tfjob.kubeflow.org/mnist-train-2 resulted in retryable error EOF"
train:	time="2019-04-18T18:12:53Z" level=info msg="kubectl get tfjob.kubeflow.org/mnist-train-2 -w -o json"
train:	time="2019-04-18T18:12:54Z" level=info msg="{\"apiVersion\": \"kubeflow.org/v1beta2\",\"kind\": \"TFJob\",\"metadata\": {\"creationTimestamp\": \"2019-04-18T18:09:08Z\",\"generation\": 1,\"name\": \"mnist-train-2\",\"namespace\": \"kubeflow\",\"ownerReferences\": [{\"apiVersion\": \"argoproj.io/v1alpha1\",\"controller\": true,\"kind\": \"Workflow\",\"name\": \"kubeflow-tf-train-7w6r9\",\"uid\": \"05e64d86-6205-11e9-a023-da0ed60f5a55\"}],\"resourceVersion\": \"4721\",\"selfLink\": \"/apis/kubeflow.org/v1beta2/namespaces/kubeflow/tfjobs/mnist-train-2\",\"uid\": \"0f2619f0-6205-11e9-a023-da0ed60f5a55\"},\"spec\": {\"tfReplicaSpecs\": {\"Worker\": {\"replicas\": 1,\"template\": {\"spec\": {\"containers\": [{\"image\": \"seldonio/deepmnistclassifier_trainer:0.1\",\"name\": \"tensorflow\",\"volumeMounts\": [{\"mountPath\": \"/data\",\"name\": \"persistent-storage\"}]}],\"restartPolicy\": \"OnFailure\",\"volumes\": [{\"name\": \"persistent-storage\",\"persistentVolumeClaim\": {\"claimName\": \"nfs-1\"}}]}},\"tfReplicaType\": \"MASTER\"}}},\"status\": {\"conditions\": [{\"lastTransitionTime\": \"2019-04-18T18:09:08Z\",\"lastUpdateTime\": \"2019-04-18T18:09:08Z\",\"message\": \"TFJob mnist-train-2 is created.\",\"reason\": \"TFJobCreated\",\"status\": \"True\",\"type\": \"Created\"}],\"replicaStatuses\": {\"Worker\": {}}}}"
train:	time="2019-04-18T18:12:54Z" level=info msg="success condition '{status.replicaStatuses.Worker.succeeded == [1]}' evaluated false"
train:	time="2019-04-18T18:12:54Z" level=info msg="0/1 success conditions matched"
train:	time="2019-04-18T18:14:13Z" level=warning msg="Json reader returned error EOF. Calling kill (usually superfluous)"
train:	time="2019-04-18T18:14:13Z" level=warning msg="Command for kubectl get -w for tfjob.kubeflow.org/mnist-train-2 exited. Getting return value using Wait"
train:	time="2019-04-18T18:14:13Z" level=info msg="readJSon failed for resource tfjob.kubeflow.org/mnist-train-2 but cmd.Wait for kubectl get -w command did not error"
train:	time="2019-04-18T18:14:13Z" level=info msg="Waiting for resource tfjob.kubeflow.org/mnist-train-2 resulted in retryable error EOF"
train:	time="2019-04-18T18:15:33Z" level=info msg="kubectl get tfjob.kubeflow.org/mnist-train-2 -w -o json"
train:	time="2019-04-18T18:15:35Z" level=info msg="{\"apiVersion\": \"kubeflow.org/v1beta2\",\"kind\": \"TFJob\",\"metadata\": {\"creationTimestamp\": \"2019-04-18T18:09:08Z\",\"generation\": 1,\"name\": \"mnist-train-2\",\"namespace\": \"kubeflow\",\"ownerReferences\": [{\"apiVersion\": \"argoproj.io/v1alpha1\",\"controller\": true,\"kind\": \"Workflow\",\"name\": \"kubeflow-tf-train-7w6r9\",\"uid\": \"05e64d86-6205-11e9-a023-da0ed60f5a55\"}],\"resourceVersion\": \"4721\",\"selfLink\": \"/apis/kubeflow.org/v1beta2/namespaces/kubeflow/tfjobs/mnist-train-2\",\"uid\": \"0f2619f0-6205-11e9-a023-da0ed60f5a55\"},\"spec\": {\"tfReplicaSpecs\": {\"Worker\": {\"replicas\": 1,\"template\": {\"spec\": {\"containers\": [{\"image\": \"seldonio/deepmnistclassifier_trainer:0.1\",\"name\": \"tensorflow\",\"volumeMounts\": [{\"mountPath\": \"/data\",\"name\": \"persistent-storage\"}]}],\"restartPolicy\": \"OnFailure\",\"volumes\": [{\"name\": \"persistent-storage\",\"persistentVolumeClaim\": {\"claimName\": \"nfs-1\"}}]}},\"tfReplicaType\": \"MASTER\"}}},\"status\": {\"conditions\": [{\"lastTransitionTime\": \"2019-04-18T18:09:08Z\",\"lastUpdateTime\": \"2019-04-18T18:09:08Z\",\"message\": \"TFJob mnist-train-2 is created.\",\"reason\": \"TFJobCreated\",\"status\": \"True\",\"type\": \"Created\"}],\"replicaStatuses\": {\"Worker\": {}}}}"
train:	time="2019-04-18T18:15:35Z" level=info msg="success condition '{status.replicaStatuses.Worker.succeeded == [1]}' evaluated false"
train:	time="2019-04-18T18:15:35Z" level=info msg="0/1 success conditions matched"
train:	time="2019-04-18T18:17:07Z" level=warning msg="Json reader returned error EOF. Calling kill (usually superfluous)"
train:	time="2019-04-18T18:17:07Z" level=warning msg="Command for kubectl get -w for tfjob.kubeflow.org/mnist-train-2 exited. Getting return value using Wait"
train:	time="2019-04-18T18:17:07Z" level=info msg="readJSon failed for resource tfjob.kubeflow.org/mnist-train-2 but cmd.Wait for kubectl get -w command did not error"
train:	time="2019-04-18T18:17:07Z" level=info msg="Waiting for resource tfjob.kubeflow.org/mnist-train-2 resulted in retryable error EOF"
train:	time="2019-04-18T18:22:27Z" level=info msg="kubectl get tfjob.kubeflow.org/mnist-train-2 -w -o json"
train:	time="2019-04-18T18:22:28Z" level=info msg="{\"apiVersion\": \"kubeflow.org/v1beta2\",\"kind\": \"TFJob\",\"metadata\": {\"creationTimestamp\": \"2019-04-18T18:09:08Z\",\"generation\": 1,\"name\": \"mnist-train-2\",\"namespace\": \"kubeflow\",\"ownerReferences\": [{\"apiVersion\": \"argoproj.io/v1alpha1\",\"controller\": true,\"kind\": \"Workflow\",\"name\": \"kubeflow-tf-train-7w6r9\",\"uid\": \"05e64d86-6205-11e9-a023-da0ed60f5a55\"}],\"resourceVersion\": \"4721\",\"selfLink\": \"/apis/kubeflow.org/v1beta2/namespaces/kubeflow/tfjobs/mnist-train-2\",\"uid\": \"0f2619f0-6205-11e9-a023-da0ed60f5a55\"},\"spec\": {\"tfReplicaSpecs\": {\"Worker\": {\"replicas\": 1,\"template\": {\"spec\": {\"containers\": [{\"image\": \"seldonio/deepmnistclassifier_trainer:0.1\",\"name\": \"tensorflow\",\"volumeMounts\": [{\"mountPath\": \"/data\",\"name\": \"persistent-storage\"}]}],\"restartPolicy\": \"OnFailure\",\"volumes\": [{\"name\": \"persistent-storage\",\"persistentVolumeClaim\": {\"claimName\": \"nfs-1\"}}]}},\"tfReplicaType\": \"MASTER\"}}},\"status\": {\"conditions\": [{\"lastTransitionTime\": \"2019-04-18T18:09:08Z\",\"lastUpdateTime\": \"2019-04-18T18:09:08Z\",\"message\": \"TFJob mnist-train-2 is created.\",\"reason\": \"TFJobCreated\",\"status\": \"True\",\"type\": \"Created\"}],\"replicaStatuses\": {\"Worker\": {}}}}"
train:	time="2019-04-18T18:22:28Z" level=info msg="success condition '{status.replicaStatuses.Worker.succeeded == [1]}' evaluated false"
train:	time="2019-04-18T18:22:28Z" level=info msg="0/1 success conditions matched"
train:	time="2019-04-18T18:24:08Z" level=warning msg="Json reader returned error EOF. Calling kill (usually superfluous)"
train:	time="2019-04-18T18:24:08Z" level=warning msg="Command for kubectl get -w for tfjob.kubeflow.org/mnist-train-2 exited. Getting return value using Wait"
train:	time="2019-04-18T18:24:08Z" level=info msg="readJSon failed for resource tfjob.kubeflow.org/mnist-train-2 but cmd.Wait for kubectl get -w command did not error"
train:	time="2019-04-18T18:24:08Z" level=info msg="Waiting for resource tfjob.kubeflow.org/mnist-train-2 resulted in retryable error EOF"
train:	time="2019-04-18T18:24:08Z" level=warning msg="Waiting for resource tfjob.kubeflow.org/mnist-train-2 resulted in timeout due to repeated errors"
train:	time="2019-04-18T18:24:09Z" level=fatal msg="timed out waiting for the condition"
!kubectl get tfjob 
NAME            STATE     AGE
mnist-train-2   Created   1h
!
!kubectl describe tfjob mnist-train-2
Name:         mnist-train-2
Namespace:    kubeflow
Labels:       <none>
Annotations:  <none>
API Version:  kubeflow.org/v1beta2
Kind:         TFJob
Metadata:
  Creation Timestamp:  2019-04-18T18:09:08Z
  Generation:          1
  Owner References:
    API Version:     argoproj.io/v1alpha1
    Controller:      true
    Kind:            Workflow
    Name:            kubeflow-tf-train-7w6r9
    UID:             05e64d86-6205-11e9-a023-da0ed60f5a55
  Resource Version:  4721
  Self Link:         /apis/kubeflow.org/v1beta2/namespaces/kubeflow/tfjobs/mnist-train-2
  UID:               0f2619f0-6205-11e9-a023-da0ed60f5a55
Spec:
  Tf Replica Specs:
    Worker:
      Replicas:  1
      Template:
        Spec:
          Containers:
            Image:  seldonio/deepmnistclassifier_trainer:0.1
            Name:   tensorflow
            Volume Mounts:
              Mount Path:  /data
              Name:        persistent-storage
          Restart Policy:  OnFailure
          Volumes:
            Name:  persistent-storage
            Persistent Volume Claim:
              Claim Name:  nfs-1
      Tf Replica Type:     MASTER
Status:
  Conditions:
    Last Transition Time:  2019-04-18T18:09:08Z
    Last Update Time:      2019-04-18T18:09:08Z
    Message:               TFJob mnist-train-2 is created.
    Reason:                TFJobCreated
    Status:                True
    Type:                  Created
  Replica Statuses:
    Worker:
Events:
  Type     Reason                          Age   From         Message
  ----     ------                          ----  ----         -------
  Warning  SettedPodTemplateRestartPolicy  72m   tf-operator  Restart policy in pod template will be overwritten by restart policy in replica spec
  Normal   SuccessfulCreatePod             72m   tf-operator  Created pod: mnist-train-2-worker-0
  Normal   SuccessfulCreateService         72m   tf-operator  Created service: mnist-train-2-worker-0

**Comment by ukclivecox** [comment]
I would check the logs of the pod running the training - it should be easy to find hopefully.

**Comment by DavidLangworthy** [comment]
@cliveseldon that did it.  Thank you.  It's missing the claim below.  How do I fix this?

mnist-train-2-worker-0
persistentvolumeclaim "nfs-1" not found

I am running on AKS if that makes any difference.

**Comment by ukclivecox** [comment]
You need an NFS volume. There are some [docs](https://github.com/kubeflow/example-seldon/blob/master/nfs.md)

**Comment by DavidLangworthy** [comment]
@cliveseldon does it actually have to be NFS or will Azure managed premium work?  Something like this:

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi

**Comment by ukclivecox** [comment]
Maybe. NFS will be ReadWriteMany so maybe as longs you ensure only 1 training or inference job is running at any 1 time. Be great to add this as a PR if it works.

**Comment by DavidLangworthy** [comment]
@cliveseldon Thanks.  I'll give it a go.

**Comment by DavidLangworthy** [comment]
@cliveseldon the above did work so long as I was careful not to run more than one job at a time.  To get ReadWriteMany on Azure I created a different storage class as described here [https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv](url).

**Comment by ukclivecox** [comment]
Great to know. Glad its working.
